export default {
  success: "success",
  error: "error",
  tabs: document.querySelector(".header__list"),
  tabsBtn: document.querySelectorAll(".header__item"),
  contents: document.querySelectorAll(".contents"),
  singleTab: document.querySelector(".single"),
  selects: document.querySelectorAll("select"),
  selectsPair: document.querySelectorAll(".select-pair"),
  selectFrom: document.querySelector("#from"),
  selectTo: document.querySelector("#to"),
  inputAmount: document.querySelector("#amount"),
  form: document.querySelector(".convert-form"),
  resultFrom: document.querySelector(".result-item--from"),
  resultTo: document.querySelector(".result-item--to"),
  exchangeRates: document.querySelector(".exchange-rates"),
  lastUpdateDate: document.querySelector(".update-time"),
  switchCurrenciesBtn: document.querySelector(".switch-currencies"),
  singleCurrency: document.querySelector(".single__currency"),
  singleCurrencyList: document.querySelector(".single__currency-list"),
  singleSelect: document.querySelector("#singleSelect"),
};
